title: Lessons I Give Myself 
description: Lessons I Give Myself
author: Paul Weidinger
github: https://github.com/pweids
about: I'm a programmer, reader, thinker, and sometimes a writer.
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/fpweidinger"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/paulweidinger"
    - icon: fa-github
      link: "https://github.com/pweids"

share:
  twitter_username: fpweidinger

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://fpaulw.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
